# Generated by Django 2.2.5 on 2021-01-24 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfiles',
            fields=[
                ('user', models.OneToOneField(on_delete=None, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('city', models.CharField(default='Anonymous', max_length=20)),
                ('country', models.CharField(default='Anonymous', max_length=20)),
                ('phone', models.IntegerField(default=0)),
                ('img', models.ImageField(upload_to='user_images/')),
            ],
        ),
    ]
