# Generated by Django 3.1.5 on 2021-05-12 10:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('city', models.CharField(default='Anonymous', max_length=20)),
                ('country', models.CharField(default='Anonymous', max_length=20)),
                ('phone', models.BigIntegerField(default=0)),
                ('img', models.ImageField(upload_to='user_images/')),
                ('img_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
