# Generated by Django 2.2.5 on 2021-01-27 20:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login_module', '0003_auto_20210125_0739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userProfiles',
            new_name='UserProfile',
        ),
    ]
